# This is a config for E2B sandbox template.
# You can use template ID (9m9qt604lcyu7ypfajgo) or template name (vibe-nextjs-00001) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-00001") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-00001") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-00001')

team_id = "d3a04693-4731-4fc6-8508-fd17816bf137"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-00001"
template_id = "9m9qt604lcyu7ypfajgo"
